M48
; DRILL file {KiCad (5.99.0-10573-gc33b2cfa8d)} date Wednesday, May 19, 2021 at 02:35:51 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-05-19T14:35:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10573-gc33b2cfa8d)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0906
%
G90
G05
T1
X3.7462Y-5.9996
X3.9738Y-5.9996
T2
X4.2938Y-5.9347
X4.7662Y-5.9347
T0
M30
